title: Ashenafi Gurmu, PhD
tagline: Senior Data Scientist | Generative AI Technical Lead
description: Senior GenAI Architect and LLMOps Engineer delivering cutting-edge agentic AI systems, advanced RAG pipelines, and fine-tuned LLMs in federal and enterprise environments. Specialized in LangGraph, Azure OpenAI, and secure AI deployment.
url: "https://gurmu.github.io"
baseurl: "/portfolio"
email: agurmu@gmail.com
phone: "+1 240-755-9064"
linkedin: https://www.linkedin.com/in/ashenafi-gurmu/
github: https://github.com/gurmu
permalink: /blog/:title/
timezone: America/New_York
plugins:
  - jekyll-feed
